services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django-spr411:latest
    container_name: django-spr411-web
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    restart: unless-stopped
