# Generated by Django 6.0.6 on 2026-06-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books'), ('furniture', 'Furniture'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
